/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.104
 * Generated at: 2020-07-07 08:29:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.dept;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.bit.dept.DeptSQL;
import java.util.ArrayList;
import com.bit.emp.EmpDto;
import com.bit.emp.EmpSQL;
import com.bit.util.MyOracle;

public final class detail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"EUC-KR\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<style>\n");
      out.write("a {\n");
      out.write("\ttext-decoration: none;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../template/header.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("path", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("../", request.getCharacterEncoding()), out, false);
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../template/menu.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("path", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("../", request.getCharacterEncoding()), out, false);
      com.bit.dept.DeptDto bean = null;
      bean = (com.bit.dept.DeptDto) _jspx_page_context.getAttribute("bean", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (bean == null){
        bean = new com.bit.dept.DeptDto();
        _jspx_page_context.setAttribute("bean", bean, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("<!-- EmpDto타입 bean 선언-->\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("bean"), request);

		DeptSQL dept = new DeptSQL();
		dept.detail(bean);
	
      out.write("<br>\n");
      out.write("\t<br>\n");
      out.write("\t<br>\n");
      out.write("\t<h1 align=\"center\">");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.bit.dept.DeptDto)_jspx_page_context.findAttribute("bean")).getNum())));
      out.write("'s\n");
      out.write("\t\tDetail Page\n");
      out.write("\t</h1>\n");
      out.write("\t");

		System.out.println("111111111111111");
	
      out.write("<table width=\"45%\" align=\"center\">\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<td colspan=\"2\" align=\"right\"><a style=\"color: black;\"\n");
      out.write("\t\t\t\thref=\"delete.jsp\"><button>Delete</button></a></td>\n");
      out.write("\t\t</tr>\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<td>&nbsp;</td>\n");
      out.write("\t\t</tr>\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t");

				System.out.println("222");
			
      out.write("<th bgcolor=\"#6262d7\" style=\"color: white;\" width=\"120\">ID</th>\n");
      out.write("\t\t\t<td align=\"center\" width=\"300\">");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.bit.dept.DeptDto)_jspx_page_context.findAttribute("bean")).getId())));
      out.write("</td>\n");
      out.write("\t\t</tr>\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<th bgcolor=\"#6262d7\" style=\"color: white;\">Password</th>\n");
      out.write("\t\t\t<td align=\"center\">");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.bit.dept.DeptDto)_jspx_page_context.findAttribute("bean")).getPw())));
      out.write("</td>\n");
      out.write("\t\t</tr>\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<th bgcolor=\"#6262d7\" style=\"color: white;\">Name</th>\n");
      out.write("\t\t\t<td align=\"center\">");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.bit.dept.DeptDto)_jspx_page_context.findAttribute("bean")).getName())));
      out.write("</td>\n");
      out.write("\t\t</tr>\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<th bgcolor=\"#6262d7\" style=\"color: white;\">Level</th>\n");
      out.write("\t\t\t<td align=\"center\">");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.bit.dept.DeptDto)_jspx_page_context.findAttribute("bean")).getLev())));
      out.write("</td>\n");
      out.write("\t\t</tr>\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<th bgcolor=\"#6262d7\" style=\"color: white;\">Join Date</th>\n");
      out.write("\t\t\t<td align=\"center\">");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.bit.dept.DeptDto)_jspx_page_context.findAttribute("bean")).getDtime())));
      out.write("</td>\n");
      out.write("\t\t</tr>\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<td>&nbsp;</td>\n");
      out.write("\t\t</tr>\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t");

				System.out.println("33");
			
      out.write("<td colspan=\"2\" align=\"right\"><a style=\"color: black;\"\n");
      out.write("\t\t\t\thref=\"edit.jsp\"><button>Edit</button></a> <a style=\"color: black;\"\n");
      out.write("\t\t\t\thref=\"list.jsp\"><button>Back</button></a></td>\n");
      out.write("\t\t</tr>\n");
      out.write("\n");
      out.write("\t</table>\n");
      out.write("\t<br>\n");
      out.write("\t<br>\n");
      out.write("\t<br>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../template/footer.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("path", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("../", request.getCharacterEncoding()), out, false);
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
