/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.104
 * Generated at: 2020-07-03 08:26:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.emp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/emp/../template/menu.jspf", Long.valueOf(1593763521486L));
    _jspx_dependants.put("/emp/../template/footer.jspf", Long.valueOf(1593762998802L));
    _jspx_dependants.put("/emp/../template/header.jspf", Long.valueOf(1593764788040L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;



	int p = 1;
	String param = request.getParameter("page"); //페이지누르면 파라미터로 페이지번호 받음
	if(param != null){
		p = Integer.parseInt(param);
	}
	int startNum = 1+ (p-1)*20; // 1  11 21 31 41 ....
	int endNum = 20 +(p-1)*20;	// 10 20 30 40 50 .....
	String sql = "select * from (select rownum as rn, sabun, name, hiredate, pay from";
	sql+="(select * from emp01 order by sabun desc)) where rn between "+startNum+" and "+endNum;
	int cadinality = 0;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("a {\r\n");
      out.write("\ttext-decoration: none\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");

  //	request.setCharacterEncoding("EUC-KR");

	String url = "jdbc:oracle:thin:@localhost:1521:xe";
	String user = "scott";
	String password = "tiger";
	String driver = "oracle.jdbc.driver.OracleDriver";
	Class.forName(driver);
	java.util.Properties info = new java.util.Properties();
	info.setProperty("user", user);
	info.setProperty("password", password);
	java.sql.Connection conn = null;
	java.sql.Statement stmt = null;
	java.sql.ResultSet rs = null;  

      out.write("<table border = \"0\" width=\"100%\" height = \"100%\" align=\"center\" bgcolor = \"white\">\r\n");
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"6\" >\r\n");
      out.write("\t\t\t<img src=\"/web05/img/img2.png\">\r\n");
      out.write("\t\t\t<img src=\"/web05/img/char.png\">\r\n");
      out.write("\t\t\t<table align = \"right\">\r\n");
      out.write("\t\t\t<tr><td>\r\n");
      out.write("\t\t\t<label>\r\n");
      out.write("\t\t\t");

			Object obj=null;
			try{
			 obj = session.getAttribute("name");
			//String loginName = (String)session.getAttribute("name");

			if(obj != null){
				String loginName = (String)obj;
				out.print(loginName+" login");
			}
			
			
			}catch(Exception e){
				
			}
			
      out.write("</label></td></tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>");
      out.write("<tr align=\"center\">\r\n");
      out.write("\t\t\t<td bgcolor=\"#ff6666\"> &nbsp;</td>\r\n");
      out.write("\t\t\t<th width=\"100\" bgcolor=\"#ff6666\"><a style= \"color:white;\" href=\"/web05/\">HOME</a></th>\r\n");
      out.write("\t\t\t<td width=\"100\" bgcolor=\"#ff6666\"><a style= \"color:white;\" href=\"/web05/emp/list.jsp\">E M P</a></td>\r\n");
      out.write("\t\t\t<td width=\"100\" bgcolor=\"#ff6666\"><a style= \"color:white;\" href=\"/web05/dept/list.jsp\">DEPT</a></td>\r\n");
      out.write("\t\t\t");

			
			//Object obj = session.getAttribute("name");
			if(obj == null){
			
      out.write("<td width=\"100\" bgcolor=\"#ff6666\"><a style= \"color:white;\" href=\"/web05/login/form.jsp\">LOGIN</a></td>\r\n");
      out.write("\t\t\t");

			}else{
			
      out.write("<td width=\"100\" bgcolor=\"#ff6666\"><a style= \"color:white;\" href=\"/web05/login/logout.jsp\">LOGOUT</a></td>\r\n");
      out.write("\t\t\t");

			}
			
      out.write("<td bgcolor=\"#ff6666\">&nbsp;</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"6\"> \r\n");
      out.write("\t\t<!-- content start -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
      out.write("<h1 align = \"center\">List Page</h1>\r\n");
      out.write("\t<center>\r\n");
      out.write("\t<a style= \"color:#ff6d6e;\" href =\"add.jsp\">ADD</a>\r\n");
      out.write("\t</center>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<table width=\"70%\" border=\"0\" cellspacing=\"0\" align=\"center\">\r\n");
      out.write("\r\n");
      out.write("\t\t<tr align=\"center\">\r\n");
      out.write("\t\t\t<th style=\"color: white;\" bgcolor=\"#ff6e6e\">사번</th>\r\n");
      out.write("\t\t\t<th style=\"color: white;\" bgcolor=\"#ff6e6e\">이름</th>\r\n");
      out.write("\t\t\t<th  style=\"color: white;\" bgcolor=\"#ff6e6e\">입사일</th>\r\n");
      out.write("\t\t\t<th  style=\"color: white;\" bgcolor=\"#ff6e6e\">연봉</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");

			try{
			 conn = DriverManager.getConnection(url, info);
			 stmt = conn.createStatement();
				rs = stmt.executeQuery("select count(*) from emp01");
				if(rs.next()) cadinality = rs.getInt(1);
				stmt.close();
				
				stmt = conn.createStatement();
				rs = stmt.executeQuery(sql);
				int cnt = 0;
				while (rs.next()) {
					String bg = "";
					if (cnt++ % 2 == 1)
						bg = "bgcolor = \"#fac8c8\"";
		
      out.write("<tr align=\"center\">\r\n");
      out.write("\t\t\t<td ");
      out.print(bg);
      out.write("><a style=\"color: black;\" href=\"detail.jsp?idx=");
      out.print(rs.getInt("sabun"));
      out.write('"');
      out.write('>');
      out.print(rs.getInt("sabun"));
      out.write("</a></td>\r\n");
      out.write("\t\t\t<td ");
      out.print(bg);
      out.write("><a style=\"color: black;\" href=\"detail.jsp?idx=");
      out.print(rs.getInt("sabun"));
      out.write('"');
      out.write('>');
      out.print(rs.getString("name"));
      out.write("</a></td>\r\n");
      out.write("\t\t\t<td ");
      out.print(bg);
      out.write("><a style=\"color: black;\" href=\"detail.jsp?idx=");
      out.print(rs.getInt("sabun"));
      out.write('"');
      out.write('>');
      out.print(rs.getDate("hiredate"));
      out.write("</a></td>\r\n");
      out.write("\t\t\t<td ");
      out.print(bg);
      out.write("><a style=\"color: black;\" href=\"detail.jsp?idx=");
      out.print(rs.getInt("sabun"));
      out.write('"');
      out.write('>');
      out.print(rs.getInt("pay"));
      out.write("</a></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");

				}//while
			} finally {
				if (stmt != null)
					stmt.close();
				if (conn != null)
					conn.close();
			}
		
      out.write("</table>\r\n");
      out.write("\t<br><br>\r\n");
      out.write("\t<center>\r\n");
      out.write("\t\r\n");

	//cadinality = 817;
	int left = cadinality%20;
	int leftPage = 0;
	if(left != 0) leftPage = 1;
	int limit = (cadinality-left)/20+leftPage;
	
	/*
	817
	40 페이지
	엔드 40
	
	1~10 페이지  일때는 엔드가 10 
	
	33
	
	3+나머지 
	
	1~10     %10 1  limit 10 
	11 20	 %10 2 	limit 20
	21	30	 %10 3  limit 30 
	
	*/
	int pageLang = 5;
	int start = 0;
	int leftEnd = 0;
	if(p%pageLang != 0) leftEnd  = 1;
	int end = ((p-p%pageLang)/pageLang+leftEnd)*pageLang;
	//int end = start + 10;
	
	if(p<pageLang+1){
		start = 0;
	}else{
		start = end-pageLang;
		out.print("<a style= \"color:#ff6d6e;\" href=\"list.jsp?page="+(end-pageLang)+"\"> [prev] </a>");
	}//if
	
	if(end > limit){
		end = limit;
		start = end - limit%pageLang;
	}//if
	
	for(int i = start; i< end; i++){
		
      out.write("<a style= \"color:#ff6d6e;\" href =\"list.jsp?page=");
      out.print( i+1);
      out.write('"');
      out.write('>');
      out.write('[');
      out.print( i+1 );
      out.write("]</a>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
	
	}//for
	
	if(end < limit){
	out.print("<a style= \"color:#ff6d6e;\" href=\"list.jsp?page="+(end+1)+"\"> [next] </a>");
	}

      out.write("</center>\r\n");
      out.write("<br><br>\r\n");
      out.write("\t\r\n");
      out.write("<!-- content end -->\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr align = \"center\">\r\n");
      out.write("\t\t\t<!-- footer start-->\r\n");
      out.write("\t\t\t<td bgcolor=\"#ff6666\" ></td>\r\n");
      out.write("\t\t\t<td style= \"color:white;\" colspan=\"4\" bgcolor=\"#ff6666\" >비트캠프 서울시 서초구 강남대로 459 (서초동,\r\n");
      out.write("\t\t\t\t백암빌딩)｜ 사업자등록번호 : 214-85-24928 <br>(주)비트컴퓨터 서초본원 대표이사 : 조현정 / 문의\r\n");
      out.write("\t\t\t\t: 02-3486-9600 / 팩스 : 02-6007-1245 <br> 통신판매업 신고번호 : 제 서초-00098호 /\r\n");
      out.write("\t\t\t\t개인정보보호관리책임자 : 최종진<br> Copyright (c) 비트캠프 All rights reserved.\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td bgcolor=\"#ff6666\" ></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- footer end-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
