/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.104
 * Generated at: 2020-07-08 06:08:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.template;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.bit.dept.DeptSQL;
import com.bit.dept.DeptDto;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      com.bit.dept.DeptDto login = null;
      synchronized (session) {
        login = (com.bit.dept.DeptDto) _jspx_page_context.getAttribute("login", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (login == null){
          login = new com.bit.dept.DeptDto();
          _jspx_page_context.setAttribute("login", login, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\n');

	String user = "scott";
	String pw = "tiger";
	String driver = "oracle.jdbc.driver.OracleDriver";
	String url = "jdbc:oracle:thin:@127.0.0.1:1521:xe";
	java.util.Properties info = new java.util.Properties();
	java.sql.Connection conn = null;
	java.sql.Statement stmt = null;
	java.sql.ResultSet rs = null;
	info.setProperty("user", user);
	info.setProperty("password", pw);
	Class.forName(driver);

	request.setCharacterEncoding("EUC-KR");
	DeptDto log = (DeptDto) session.getAttribute("login");
	DeptSQL dept = new DeptSQL();
	dept.detail(log);

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<table border=\"0\" width=\"100%\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t");

		if (!log.isResult()) {
	
      out.write("\n");
      out.write("\t<tr>\n");
      out.write("\t\t<!-- login  -->\n");
      out.write("\t\t<td colspan=\"5\" style=\"text-align: right;\"><a\n");
      out.write("\t\t\tstyle=\"color: black; font-size: 60%;\" href=\"");
      out.print(request.getParameter("path") );
      out.write("login/form.jsp\">로그인</a>\n");
      out.write("\t\t\t<a style=\"color: black; font-size: 60%;\" href=\"#\">회원가입</a></td>\n");
      out.write("\t</tr>\n");
      out.write("\t");

		} else {
	
      out.write("\n");
      out.write("\t<tr>\n");
      out.write("\t\t<!-- login  -->\n");
      out.write("\t\t<td colspan=\"5\" style=\"text-align: right;\"><a\n");
      out.write("\t\t\tstyle=\"color: black; font-size: 60%;\" href=\"");
      out.print(request.getParameter("path") );
      out.write("dept/detail.jsp?num=");
      out.print(log.getNum());
      out.write('"');
      out.write('>');
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.bit.dept.DeptDto)_jspx_page_context.findAttribute("login")).getName())));
      out.write("님 환영합니다.</a> <a\n");
      out.write("\t\t\tstyle=\"color: black; font-size: 60%;\" href=\"");
      out.print(request.getParameter("path") );
      out.write("login/logout.jsp\">로그아웃</a></td>\n");
      out.write("\t</tr>\n");
      out.write("\n");
      out.write("\t");

		}
	
      out.write("\n");
      out.write("\t<tr height=\"40\">\n");
      out.write("\t\t<!-- logo -->\n");
      out.write("\t\t<td colspan=\"5\"><a\n");
      out.write("\t\t\thref=\"");
      out.print(request.getParameter("path"));
      out.write("index.jsp\"><img\n");
      out.write("\t\t\t\tsrc=\"");
      out.print(request.getParameter("path"));
      out.write("img/char.png\"></a></td>\n");
      out.write("\n");
      out.write("\t</tr>\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
